name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release-package:
    if: "contains(github.event.head_commit.message, 'Bump version')"
    name: Release package on PyPI
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip3 install -U setuptools twine wheel auditwheel
    - name: Build package
      run: |
        python3 setup.py bdist_wheel sdist --format=gztar
        mv dist/*.whl .
        auditwheel repair -w dist *.whl
        rm *.whl
        ls
        ls dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: "${{ secrets.PYPI_API_TOKEN }}"